# Generated by Django 3.1.7 on 2021-03-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
        ('categories', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='category', to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='books',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='writer', to='writer.writer'),
        ),
    ]
