# Generated by Django 3.1.7 on 2021-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('writer_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
