# Generated by Django 3.1.7 on 2021-03-20 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField(default=0.0)),
                ('review', models.CharField(default='', max_length=225)),
                ('review_date', models.DateField(auto_now=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
