# Generated by Django 3.1.5 on 2021-03-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='book_id',
        ),
    ]
